# Generated by Django 6.0.6 on 2026-08-18 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_user', '0002_compte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compte',
            old_name='nom',
            new_name='username',
        ),
    ]
