# Generated by Django 6.0.6 on 2026-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=180)),
                ('prenom', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('derniere_modification', models.DateField(auto_now=True)),
            ],
        ),
    ]
