# Generated by Django 6.0.6 on 2026-08-19 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adressebook', '0002_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='adresse',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
