# Generated by Django 6.0.6 on 2026-08-20 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adressebook', '0003_contact_adresse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(verbose_name=180)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='Categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adressebook.categorie'),
        ),
    ]
